openapi: 3.0.0
info:
  title: MAOS Core API
  version: 1.0.0
  description: API for managing invocation jobs and configurations in the MAOS system

servers:
  - url: https://api.example.com/v1

security:
  - bearerAuth: []
  - trace: []

paths:
  /health:
    $ref: "./resources/health.yaml"

  /v1/config:
    $ref: "./resources/config.yaml"

  /v1/invocations/async:
    $ref: "./resources/invocation/create_async.yaml"

  /v1/invocations/sync:
    $ref: "./resources/invocation/create_sync.yaml"

  /v1/invocations/next:
    $ref: "./resources/invocation/next.yaml"

  /v1/invocations/{id}:
    $ref: "./resources/invocation/get.yaml"

  /v1/invocations/{invoke_id}/response:
    $ref: "./resources/invocation/response.yaml"

  /v1/invocations/{invoke_id}/error:
    $ref: "./resources/invocation/error.yaml"

  /v1/completion/models:
    $ref: "./resources/completion/models.yaml"

  /v1/completion:
    $ref: "./resources/completion/index.yaml"

  /v1/embedding/models:
    $ref: "./resources/embedding/models.yaml"

  /v1/embedding:
    $ref: "./resources/embedding/index.yaml"

  /v1/vector/list:
    $ref: "./resources/vector/list.yaml"

  /v1/vector/collection:
    $ref: "./resources/vector/collections.yaml"

  /v1/vector/collection/{name}:
    $ref: "./resources/vector/collection.yaml"

  /v1/rerank/models:
    $ref: "./resources/rerank/models.yaml"

  /v1/rerank:
    $ref: "./resources/rerank/index.yaml"

  /v1/mcp:
    $ref: "./resources/mcp/index.yaml"

  /v1/mcp/agents/{agent}:
    $ref: "./resources/mcp/agent.yaml"

  /v1/mcp/message:
    $ref: "./resources/mcp/message.yaml"

  /v1/mcp/invocations:
    $ref: "./resources/mcp/invocation_request.yaml"

  /v1/mcp/invocations/{id}:
    $ref: "./resources/mcp/invocation_response.yaml"

  /v1/admin/api_tokens:
    $ref: "./resources/admin/api_tokens.yaml"

  /v1/admin/api_tokens/{id}:
    $ref: "./resources/admin/api_token.yaml"

  /v1/admin/actors:
    $ref: "./resources/admin/actors.yaml"

  /v1/admin/actors/{id}:
    $ref: "./resources/admin/actor.yaml"

  /v1/admin/deployments:
    $ref: "./resources/admin/deployments.yaml"

  /v1/admin/deployments/{id}:
    $ref: "./resources/admin/deployment.yaml"

  /v1/admin/deployments/{id}/restart:
    $ref: "./resources/admin/deployment_restart.yaml"

  /v1/admin/deployments/{id}/submit:
    $ref: "./resources/admin/deployment_submit.yaml"

  /v1/admin/deployments/{id}/publish:
    $ref: "./resources/admin/deployment_publish.yaml"

  /v1/admin/deployments/{id}/reject:
    $ref: "./resources/admin/deployment_reject.yaml"

  /v1/admin/deployments/{id}/result:
    $ref: "./resources/admin/deployment_result.yaml"

  /v1/admin/configs/{id}:
    $ref: "./resources/admin/config.yaml"

  /v1/admin/setting:
    $ref: "./resources/admin/setting.yaml"

  /v1/admin/reference_config_suites:
    $ref: "./resources/admin/reference_config_suites.yaml"

  /v1/admin/reference_config_suites/sync:
    $ref: "./resources/admin/reference_config_suites_sync.yaml"

  /v1/admin/secrets:
    $ref: "./resources/admin/secrets.yaml"

  /v1/admin/secrets/{name}:
    $ref: "./resources/admin/secret.yaml"

  /v1/admin/metrics/pods:
    $ref: "./resources/admin/metrics_pods.yaml"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      description: Enter the pre-assigned API key as a bearer token
    trace:
      type: apiKey
      in: header
      name: MAOS-TRACE-ID
      description: The unique trace id.

tags:
  - name: Configuration
    description: Operations related to caller configuration
  - name: Invocation
    description: Operations related to invocation jobs
  - name: Completion
    description: Operations involving LLM completion models
  - name: Embedding
    description: Operations involving embedding models and texts
  - name: VectorStore
    description: Operations involving vector store
  - name: Rerank
    description: Operations involving rerank models and texts
  - name: Admin
    description: Operations involving admin tasks
  - name: Health
    description: Operations related to system health

x-namespaces:
  - Maos
